name: Go CI

on:
  push:
    branches: [ main ]
    paths:
      - 'go/**'
      - 'test-vectors/**'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - 'test-vectors/**'
      - '.github/workflows/go.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    
    - name: Verify dependencies
      working-directory: ./go
      run: go mod verify
    
    - name: Build
      working-directory: ./go
      run: go build -v ./...
    
    - name: Run tests
      working-directory: ./go
      run: go test -v ./...
    
    - name: Run examples
      working-directory: ./go
      run: go run examples/hash_example.go
    
    - name: Vet
      working-directory: ./go
      run: go vet ./...
    
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Run staticcheck
      working-directory: ./go
      run: staticcheck ./...