name: JavaScript/TypeScript CI

on:
  push:
    branches: [ main ]
    paths:
      - 'js/**'
      - 'test-vectors/**'
      - '.github/workflows/js.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'js/**'
      - 'test-vectors/**'
      - '.github/workflows/js.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: js/package-lock.json
    
    - name: Install dependencies
      working-directory: ./js
      run: npm ci
    
    - name: Lint
      working-directory: ./js
      run: npm run lint
    
    - name: Build
      working-directory: ./js
      run: npm run build
    
    - name: Test
      working-directory: ./js
      run: npm test
    
    - name: Run example
      working-directory: ./js
      run: |
        node -e "require('./dist/examples/hash_example');"